[theme]
# The primary accent color for interactive elements (e.g., Primary Buttons, Sliders)
primaryColor = "#008080"

# The base theme. Options: "light" or "dark"
base = "light"

# The main background color of the app
backgroundColor = "#FFFFFF"

# The background color for the sidebar and st.container(border=True)
secondaryBackgroundColor = "#F3F2F1"

# The global text color
textColor = "#323130"

# The global font family. Options: "sans serif", "serif", "monospace"
font = "sans serif"

#[client]
# Removes the "Run" / "Stop" icons in the top right
#toolbarMode = "minimal"

[browser]
# Removes the "Share" and "Deploy" buttons
gatherUsageStats = false

#[ui]
# This hides the 'X' button and the menu completely when combined with CSS
#hideTopBar = true

[server]
# Optimizes for production performance
#headless = true 
#enableCORS = false
#enableXsrfProtection = false
runOnSave = true